# https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose-swarm.yml
version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_LISTENERS: LOCAL://:9092,DOCKER://:9094
      KAFKA_ADVERTISED_LISTENERS: LOCAL://localhost:9092,DOCKER://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LOCAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#kafka-topics.sh  --zookeeper zookeeper:2181 --list
#kafka-console-consumer.sh --topic test --bootstrap-server localhost:9092 --from-beginning
#kafka-console-producer.sh --topic test --bootstrap-server localhost:9092
